services:
  web:
    build:
      context: .
    command: gunicorn testproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - 8000

nginx:
  image: nginx:latest
  container_name: test-nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - /etc/letsencrypt/live/saadalghanem.com/fullchain.pem:/etc/ssl/certs/fullchain.pem
    - /etc/letsencrypt/live/saadalghanem.com/privkey.pem:/etc/ssl/private/privkey.pem
  depends_on:
    - web

