services:
  web:
    build:
      context: .
    command: gunicorn testproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - 8000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/saadalghanem.com:/etc/ssl/certs
      - /etc/letsencrypt/live/saadalghanem.com:/etc/ssl/private
    ports:
      - "80:80"
      - "443:443"
