version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # ملف nginx.conf من مجلد nginx
    ports:
      - "80:80"
    depends_on:
      - django  # تأكد من أن Nginx يبدأ بعد Django

  django:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]  # شغيل Django على المنفذ 8000
    volumes:
      - .:/app  # ربط جميع الملفات داخل الحاوية
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: sqlite:latest  # لا تحتاج إلى PostgreSQL هنا بما أن SQLite هو المطلوب
    volumes:
      - ./db.sqlite3:/app/db.sqlite3  # ربط قاعدة البيانات مباشرة
